name: pylint-test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install typeguard==2.13 torchtyping
    - name: Running unit tests
      run: pytest
    # NOTE: will put these back eventually
    # - name: Analysing the code with pylint
    #   run: pylint --recursive=y config feature_extractor model tests
    # - name: Looking for xcxc, just in case
    #   run: |
    #     if grep -r --include='*.py' 'xcxc'; then
    #       echo "Found xcxc in the code. Please check the file."
    #       exit 1
    #     fi